### ISSUE TITLE
Unexpected Token 'import' @index.js:1

### ISSUE THREAD

**Issue by GMuthuraja** [eGust/epub-reader#1]
When I execute a  'electron-packager . --platform=darwin' to get an executable file, I got a below error:

Uncaught Exception:
/Users/NDW/Documents/myreader/epub-reader/EPub Reader-darwin-x64/EPub Reader.app/Contents/Resources/app/src/index.js:1
(function (exports, require, module, __filename, __dirname, process, global) { import { app, BrowserWindow } from 'electron'

How to overcome this issue? 

Thanks in advance.

**Comment by eGust** [comment]
Sorry I don't have experience of packaging Electron project. This project was my experiment on Electron and ReactJS, so I did not consider packaging it. 

The error message is quite common. Node uses its own module mechanism which is different from later ES one. Somehow dev mode will execute the codes with `babel-node` or compile them into ES5 first, so Node won't complain about the `import` things. Looks like `electron-packager` neither compiles the codes to ES5, nor the executable file runs with `babel-node`, then `import` becomes an issue. 

So I can only take some guesses. 
The first method is to translate the codes to ES5 with `Babel`, which should fix it for good. Maybe you can find a way out with the community of `electron-packager`. 
The second is to convert all `import`/`export` to `require`/`exports`, which I should use for server-side codes. So they will be natively supported by Node. But still possibly would get some issues if the packaged Node version was too old to support some features used in this project. 

I personally prefer the second way. If I would do some changes to this project, I would rewrite all server-side modules codes. With upgrading dependencies, the issue shall be fixed. But very unlikely I will touch this repo again. I usually use iBooks on Mac or Edge on Windows to read `EPub`s.

Anyway, thank you for paying attention to my repo. Please let me know if you find a solution to it. Good luck!

**Comment by GMuthuraja** [comment]
Hey @eGust,
Thank you for the quick response!  

Finally got a solution by following below methodologies.
Added below three lines in a separate file as a app main entry file(in this case replace index.js to es6init.js in package.json)

**es6init.js**
var path = require('path');
_var appRoot = path.join(__dirname, '..');
require('electron-compile').init(appRoot, require.resolve('./index.js'));_

Then in terminal, electron-packager  .  --platform=darwin --no-prune
Reference: https://stackoverflow.com/questions/49556041/es6-is-not-supported-after-electron-packaging/49600407

**Comment by eGust** [comment]
Great! Thanks for your helpful feedback!
